# Generated by Django 2.1.4 on 2019-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('payment_gateway', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.IntegerField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'wp_payment',
            },
        ),
    ]
