# Generated by Django 2.1.4 on 2019-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/images/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='pages/images/icon/')),
                ('font_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('display_home', models.IntegerField(default=0)),
                ('display_menu', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_page',
            },
        ),
    ]
