# Generated by Django 2.1.4 on 2019-05-13 08:50

import category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=category.models.Category.get_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Vendor'), (2, 'Supplier')], default=1)),
                ('display_home', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('display_menu', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'wp_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'Vendor'), (2, 'Supplier')], null=True)),
                ('display_home', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('display_menu', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'db_table': 'wp_subcategory',
            },
        ),
    ]
