# Generated by Django 2.1.4 on 2019-05-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('category', '0001_initial'),
        ('services_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('email_id', models.EmailField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gurden_space', models.CharField(blank=True, max_length=200)),
                ('total_capacity', models.CharField(blank=True, max_length=200)),
                ('is_hall', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('hall_capacity', models.CharField(blank=True, max_length=200)),
                ('setting_capacity', models.CharField(blank=True, max_length=200)),
                ('is_parking_capacity', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('parking_capacity', models.CharField(blank=True, max_length=200)),
                ('total_washroom', models.CharField(blank=True, max_length=200)),
                ('area_space', models.CharField(blank=True, max_length=200)),
                ('price_start', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor/images/')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='vendor/front/images/')),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='vendor/gallery/images/')),
                ('is_latest', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('display_home', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Cities')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Countries')),
                ('loc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Location')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_category.ServicesCategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory')),
            ],
            options={
                'db_table': 'wp_venue',
            },
        ),
    ]
