# Generated by Django 2.1.4 on 2019-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_category/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('display_home', models.IntegerField(default=0)),
                ('display_menu', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_services_category',
            },
        ),
        migrations.CreateModel(
            name='ServicesSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_subcategory/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('serves_cat_id', models.IntegerField(blank=True, null=True)),
                ('display_home', models.IntegerField(default=0)),
                ('display_menu', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_services_subcategory',
            },
        ),
    ]
