# Generated by Django 2.1.4 on 2019-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=20)),
                ('email_id', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('loc_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('sub_cat_id', models.IntegerField(blank=True, null=True)),
                ('services_id', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_home', models.IntegerField(default=0)),
                ('subscription_type', models.IntegerField(default=0)),
                ('package_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'wp_supplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('cat_id', models.DateTimeField(blank=True, null=True)),
                ('subcat_id', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplier_product/images/')),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('display_home', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_supplier_product',
            },
        ),
    ]
